on:

  pull_request:

    branches-ignore:

      - ''

  push:

    branches-ignore:

      - ''

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3.5.3

      with:

        fetch-depth: 0

    - name: set up JDK 11

      uses: actions/setup-java@v3.12.0

      with:

        distribution: 'zulu'
        java-version: '17'

    - name: Build Debug .apk
      run: |
        chmod +x gradlew
        ./gradlew assembleDebug
  
    - name : upload apk
      uses: actions/upload-artifact@v3.1.2
      with:
        name: app-release
        path: FCL/build/outputs/apk/debug/*
